config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  post 'create_comments' => "articles#create_comments"
  post 'create_reply' => "articles#create_reply"
  delete 'delete_comment/:comment_id' => "articles#delete_comment", :as => :delete_comment

  resources :articles

  devise_scope :user do
    authenticated  do
      root to: 'articles#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments
  belongs_to :user

  validates :title, :body, :presence => true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  has_many :replies, class_name: "Comment", foreign_key: "reply_id"

  validates :description, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :presence => true

  has_many :articles, :dependent => :destroy
  has_many :comments, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :validate_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
       redirect_to root_path, notice: 'Article was successfully created.'
    else
     render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to root_path, notice: 'Article was successfully updated.'
    else
     render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  def create_comments
     @comments = current_user.comments.create(:description => params[:description], :article_id => params[:article_id])
     redirect_to article_path(params[:article_id])
  end

  def create_reply
    @reply = current_user.comments.create(:description => params[:description], :article_id => params[:article_id], :reply_id => params[:reply_id])
    redirect_to article_path(params[:article_id])
  end

  def delete_comment
    @comment = Comment.find(params[:comment_id])
    @article = @comment.article
    @comment.destroy
    redirect_to article_path(@article), notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def validate_user
      redirect_to root_path , notice: 'Access Denied' if current_user.id != @article.user_id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :rows => 6, :cols =>40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table border="1px">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title.truncate(30) %></td>
        <td><%= article.body.truncate(30) %></td>
        <td><%= article.user.name %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) if article.user_id == current_user.id %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } if article.user_id == current_user.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @article.title %></h3>

<p><%= simple_format @article.body %></p>

<p><strong>Author: <%= @article.user.name %> </strong></p>

<hr/>

<h3>Comments</h3>

<% @article.comments.where(:reply_id => nil).each_with_index do |comment, index| %>
    <p>
      <%= index + 1 %>. <%= comment.description%> ---- by <strong><%= comment.user.name %> </strong>
      <%= link_to 'Delete', delete_comment_path(comment) ,method: :delete, data: { confirm: 'Are you sure?' } if comment.user_id == current_user.id && comment.replies.blank? %>
    </p>

    <%= link_to 'Reply', '#', :onclick => "show_reply_box(#{comment.id})" %>

    <div class="reply_box" id="reply_box_<%= comment.id %>" >
      <%= form_tag(create_reply_path(:article_id => @article.id, :reply_id => comment.id)) do %>
          <%= text_area_tag :description,'', :rows => 4, :cols =>30 %>
          <%= submit_tag 'Reply' %>
      <% end %>
    </div>

    <div style="margin-left:50px;">
        <% comment.replies.each do |reply| %>
            <p>
              <%= reply.description %> ---- by <strong><%= reply.user.name %> </strong>
              <%= link_to 'Delete', delete_comment_path(reply) ,method: :delete, data: { confirm: 'Are you sure?' } if reply.user_id == current_user.id  %>
            </p>
        <% end %>
    </div>

<% end %>
<hr/>

<%= form_tag(create_comments_path(:article_id => @article.id)) do %>
    <%= text_area_tag :description,'', :rows => 6, :cols =>40  %>
    <%= submit_tag 'Comment' %>
<% end %>

<%= link_to 'Back', articles_path %>

<script>
  function show_reply_box(comment_id){
      $("#reply_box_"+comment_id).show();
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>

<% if user_signed_in? %>
    <div class="align_right">
      Hi <%= current_user.name %>
      <%= link_to "Logout",destroy_user_session_path, :method => :delete %>
    </div> <hr/>
<% end %>

<%= yield %>

</body>
</html>